config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'billboards#index'
  
  resources :billboards do
    resources :artists
  end
    resources :artists do
      resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :billboard
  has_many :songs, dependent: :destroy

   validates :name, uniqueness:true
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :artists, dependent: :destroy

   validates :music, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

     validates :title, :genre, presence: true 
    validates :year, numericality: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_billboard
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = @billboard.artists
  end

  def show
  end

  def new
    @artist = @billboard.artists.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @artist = @billboard.artists.new(artist_params)
    if @artist.save
      # redirect_to billboard_artists_path[@billboard]
      redirect_to [@billboard, @artist]
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to [@billboard, @artist]
    else
      render :edit
    end
  end

  def destroy 
    @artist.destroy
    redirect_to billboard_artists_path
  end

  private

  def set_billboard
    @billboard = Billboard.find(params[:billboard_id])
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name)
  end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :update, :edit, :destroy]
  
  def index
    @billboards = Billboard.all
  end

  def show
  end

  def new
    @billboard = Billboard.new
    render partial: "form"
  end

  def create
    @billboard = Billboard.new(billboard_params)

    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def create
    @billboard = Billboard.new(billboard_params)

    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to @billboard
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end



  private

    def set_billboard
      @billboard = Billboard.find(params[:id])
    end

    def billboard_params
      params.require(:billboard).permit(:music)
    end


end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  
  def index
    @songs = @artist.songs
  end

  def show
  end

  def new
    @song = @artist.songs.new
    render partial: "form"
  end

  def edit
  render partial: "form"
  end

  def create
    @song = @artist.songs.new(song_params)

    if @song.save
      redirect_to [@artist, @song]
    else
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to [@artist, @song]
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to artist_songs_path
  end

  private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title, :album, :genre, :year, :collaboration)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? 'Edit Artist' : 'Create Artist' %></h1>
<hr />
<%= form_for [@billboard, @artist] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Click on an Artist to view Songs</h1>

<ul>
  <% @artists.each do |artist| %>
    <li>
    <%= link_to artist.name, [@billboard, artist] %>
    <div></div>
    </li>
    <%end %>
    </ul>
  <%= link_to 'Create a new Artist', new_billboard_artist_path(@billboard) %>
  <div></div>
  <%= link_to 'Show all Billboards', billboards_path %>
   
   

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1><%= @billboard.music %>: <%= @artist.name %></h1>
<p><%= @artist.name %></p>
<%= link_to 'Edit Artist', edit_billboard_artist_path([@billboard, @artist]) %>
<%= link_to 'Delete Artist', [@billboard, @artist], method: :delete %>
<%= link_to 'Back To Artists', billboard_artists_path(@billboard) %>
<%= link_to 'Create a new Artist', new_billboard_artist_path(@billboard) %>


<%= link_to 'Create a new song', new_artist_song_path(@artist) %>

app/views/billboards/_form.html.erb
<h1><%= @billboard.id ? 'Edit Billboard' : 'Create Billboard' %></h1>
<hr />
<%= form_for @billboard do |f| %>
    <%= f.label :music %>
    <%= f.text_field :music, required: true %>
    <%= f.submit %>

    <% end %>

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<h1>Billboards</h1>

<ul>
<% @billboards.each do |billboard| %>
  <%= link_to billboard.music, billboard%>
  <div></div>
  <% end %>
</ul>

  <%= link_to 'Create a new billboard', new_billboard_path %> 

app/views/billboards/new.html.erb
<h1>Billboards#new</h1>
<p>Find me in app/views/billboards/new.html.erb</p>

app/views/billboards/show.html.erb
<h1><%= @billboard.music %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Artists', billboard_artists_path(@billboard) %>
<br />
<%= link_to 'Edit Billboard', edit_billboard_path(@billboard) %>
<br />
<%= link_to 'Delete Billboard', @billboard, method: :delete %>
<br />
<%= link_to 'Show all Billboards', billboards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillboardList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<h1><%= @song.id ? 'Edit Song' : 'Create Song' %></h1>
<hr />
<%= form_for [@artist, @song] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true, autofocus: true %>
  <br />
  <%= f.label :genre %>
  <%= f.text_field :genre, required: true %>
  <br />
  <%= f.label :year %>
  <%= f.text_field :year, required: true %>
  <br />
  <%= f.label :collaboration %>
  <%= f.text_field :collaboration, required: true %>
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs</h1>
<%= link_to 'Create a new song', new_artist_song_path(@artist) %>
<ul>
  <% @songs.each do |song| %>
    <li><%= link_to song.title, [@artist,song] %></li>
  <% end %>
</ul>

<%= link_to 'Back to Billboard', root_path %>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1><%= @artist.name %> - <%= @song.title %></h1>
<p><%= @song.title %></p>
<%= link_to 'Edit Song', edit_artist_song_path([@artist, @song]) %>
<%= link_to 'Delete Song', [@artist, @song], method: :delete %>
<%= link_to 'Back To Song', artist_songs_path(@artist) %>